%YAML 1.2
---
root: true
env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:react/jsx-runtime"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@next/next/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
ignorePatterns:
  - /.eslintrc.yaml
  - /next.config.js
  - /next-env.d.ts
  - /.next/**
  - /css/**
  - /data/**
  - /public/**
  - /scripts/**
rules:
  array-bracket-spacing: error
  arrow-parens: error
  block-spacing: error
  brace-style: error
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: never
      exports: never
      functions: never
  comma-spacing: error
  curly:
    - error
    - multi-or-nest
  eol-last: error
  eqeqeq: error
  func-call-spacing: error
  generator-star-spacing:
    - error
    - after
  id-match:
    - error
    - ^[A-Za-z_][A-Za-z0-9]*$
  implicit-arrow-linebreak: error
  indent:
    - error
    - 4
  jsx-quotes: error
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
      mode: strict
  keyword-spacing: error
  no-confusing-arrow: error
  no-eval: error
  no-floating-decimal: error
  no-multi-assign: error
  no-multi-spaces: error
  no-multi-str: error
  no-octal-escape: error
  no-proto: error
  no-sequences: error
  no-tabs: error
  no-template-curly-in-string: error
  no-trailing-spaces: error
  no-unneeded-ternary: error
  no-unreachable-loop: error
  no-use-before-define: "off"
  no-useless-return: error
  no-var: error
  no-whitespace-before-property: error
  nonblock-statement-body-position:
    - error
    - below
  object-property-newline: error
  one-var-declaration-per-line: error
  operator-assignment: error
  padded-blocks:
    - error
    - never
  prefer-arrow-callback: error
  prefer-const: error
  prefer-exponentiation-operator: error
  prefer-template: error
  quotes: error
  rest-spread-spacing: error
  semi: error
  semi-spacing: error
  sort-imports: error
  space-in-parens: error
  space-infix-ops: error
  spaced-comment: error
  switch-colon-spacing: error
  symbol-description: error
  template-curly-spacing: error
  template-tag-spacing: error
  unicode-bom: error
  yoda: error
  "@next/next/no-img-element": "off"
  "@typescript-eslint/no-use-before-define": error
