%YAML 1.2
---
root: true
env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:react/jsx-runtime"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@next/next/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
ignorePatterns:
  - /.eslintrc.yaml
  - /next.config.js
  - /next-env.d.ts
  - /.next/**
  - /css/**
  - /data/**
  - /public/**
  - /scripts/**
rules:
  array-bracket-spacing: warn
  arrow-parens: "off"
  block-spacing: warn
  brace-style: warn
  comma-dangle:
    - warn
    - arrays: always-multiline
      objects: always-multiline
      imports: never
      exports: never
      functions: never
  comma-spacing: error
  curly:
    - warn
    - multi-or-nest
  eol-last: warn
  eqeqeq: error
  func-call-spacing: warn
  generator-star-spacing:
    - warn
    - after
  id-match:
    - warn
    - ^[A-Za-z_][A-Za-z0-9]*$
  implicit-arrow-linebreak: error
  indent:
    - warn
    - 4
  jsx-quotes: warn
  key-spacing:
    - warn
    - beforeColon: false
      afterColon: true
      mode: strict
  keyword-spacing: warn
  no-eval: error
  no-floating-decimal: warn
  no-multi-assign: error
  no-multi-spaces: error
  no-multi-str: error
  no-octal-escape: error
  no-proto: error
  no-sequences: error
  no-tabs: warn
  no-template-curly-in-string: error
  no-trailing-spaces: warn
  no-unneeded-ternary: error
  no-unreachable-loop: warn
  no-use-before-define: "off"
  no-useless-return: warn
  no-var: error
  no-whitespace-before-property: error
  nonblock-statement-body-position:
    - warn
    - below
  object-property-newline: warn
  one-var-declaration-per-line: warn
  padded-blocks:
    - error
    - never
  prefer-arrow-callback: warn
  prefer-const: warn
  prefer-exponentiation-operator: warn
  prefer-template: warn
  quotes: error
  rest-spread-spacing: warn
  semi: warn
  semi-spacing: warn
  sort-imports: warn
  space-in-parens: warn
  space-infix-ops: warn
  spaced-comment: warn
  switch-colon-spacing: warn
  symbol-description: warn
  template-curly-spacing: warn
  template-tag-spacing: warn
  unicode-bom: error
  yoda: error
  "@next/next/no-img-element": "off"
  "@typescript-eslint/no-use-before-define": error
