/* =============================================================================
 * File:   Prebuild.js
 * Author: Cole Tobin
 * =============================================================================
 * Copyright (c) 2022 Cole Tobin
 *
 * This file is part of Arch86.
 *
 * Arch86 is free software: you can redistribute it and/or modify it under the
 *   terms of the GNU Affero General Public License as published by the Free
 *   Software Foundation, either version 3 of the License, or (at your option)
 *   any later version.
 *
 * Arch86 is distributed in the hope that it will be useful, but WITHOUT ANY
 *   WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 *   FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for
 *   more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 *   along with Arch86. If not, see <http://www.gnu.org/licenses/>.
 * =============================================================================
 */

// TODO: Convert to TypeScript

import dir from "node-dir"; // CommonJS module - must import this way
import fs from "fs";
import path from "path";

console.log("[SCRIPTS] Generating PageList.ts...");
console.log("[SCRIPTS] Generating sitemap.xml...")

const list = [];
const pagesDir = path.join(process.cwd(), "pages");
dir.files(pagesDir, { sync: true }).forEach((entry) => {
    // cleanup directory separator for Windows
    entry = entry.replace(/\\/g, "/");

    if (!entry.endsWith(".tsx"))
        return;

    // get just the URL part
    entry = entry.substring(pagesDir.length);
    entry = entry.substring(0, entry.length - ".tsx".length)

    // filter out
    if (entry === "/_app" || entry === "/404")
        return;

    // cleanup indexes
    if (entry.endsWith("index")) {
        entry = entry.substring(0, entry.length - "/index".length);
        if (entry === "")
            entry = "/"; // webroot fix
    }

    list.push(entry);
});
list.sort();

const PageListLines = [
    "// Auto-generated by /scripts/Prebuild.js",
    "// Any edits will be lost during the build process",
    "",
    "const List = [",
];
PageListLines.push(...list.map((entry) => `    "${entry}",`));
PageListLines.push(
    "] as const;",
    "",
    "export type PageListType = typeof List[number];",
    "",
    "const PageList: readonly string[] = List;",
    "export default PageList;",
    "");
fs.writeFileSync("data/PageList.ts", PageListLines.join("\n"));

const SiteMapLines = [
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
    "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">",
];
SiteMapLines.push(...list.map((entry) => `    <url><loc>https://arch86.com${entry}</loc></url>`));
SiteMapLines.push(
    "</urlset>",
    "");
fs.writeFileSync("public/sitemap.xml", SiteMapLines.join("\n"));

console.log("          Done.");
